local:
  file-storage: backend/e2e-data

opensearch:
  norms-index-name: norms_e2e
  caselaws-index-name: caselaws_e2e
  literature-index-name: literature_e2e
  documents-alias-name: documents_e2e

server:
  forward-headers-strategy: none
